### ISSUE TITLE
norm(matrix) -> opnorm(matrix) in Julia 0.7

### ISSUE THREAD

**Issue by stevengj** [JuliaMath/Calculus.jl#125]
It looks like may be using `norm(matrix)`.  In Julia 0.7, this will compute the Frobenius norm (`vecnorm` in Julia 0.6), due to JuliaLang/julia#27401.   If you want the induced/operator norm as in Julia 0.6, use `opnorm(matrix)` instead, or `Compat.opnorm(matrix)` to work in 0.6 and 0.7 (JuliaLang/Compat.jl#577).

Note that, for testing purposes, rather than `@test norm(A - B) ≤ tol`, it is usually preferred to do `@test A ≈ B` or `@test A ≈ B rtol=...` (which uses `isapprox`).

**Comment by MahyarFardin** [comment]
> It looks like may be using `norm(matrix)`. In Julia 0.7, this will compute the Frobenius norm (`vecnorm` in Julia 0.6), due to [JuliaLang/julia#27401](https://github.com/JuliaLang/julia/pull/27401). If you want the induced/operator norm as in Julia 0.6, use `opnorm(matrix)` instead, or `Compat.opnorm(matrix)` to work in 0.6 and 0.7 ([JuliaLang/Compat.jl#577](https://github.com/JuliaLang/Compat.jl/pull/577)).
> 
> Note that, for testing purposes, rather than `@test norm(A - B) ≤ tol`, it is usually preferred to do `@test A ≈ B` or `@test A ≈ B rtol=...` (which uses `isapprox`).

Hi, 
although the documentation is not clear about this, you can find that they are the same; as they define an inequality in **isapprox** function it does not really affect except this one is faster.

**Comment by stevengj** [comment]
I'm not sure what you mean by "they".  `norm(A - B) ≤ tol` is *not* the same as `A ≈ B` since the former is an absolute tolerance while the latter uses a relative tolerance by default (though you could specify `@test A ≈ B atol=tol` to get a mathematically equivalent test to `@test norm(A - B) ≤ tol`.   Also, `@test A ≈ B` has more informative printing if there is an error.

In any case, that's an aside to the reason for this issue, which is that this package was using a function (`norm`) which changed meaning in Julia 0.7, so we wanted to notify them in case they were reliant on the old behavior.   As this package declared itself to be compatible with Julia 1, with passing tests, I think this issue can be closed.
