### ISSUE TITLE
is that possible to repleace Calculus.quadgk with QuadGK.quadgk ?

### ISSUE THREAD

**Issue by nesteiner** [JuliaMath/Calculus.jl#156]
I think the usage of calculus should be united,   
![图片](https://user-images.githubusercontent.com/46296608/164965203-a5abb6af-77a2-4157-823e-31cab4c5b339.png)

why don't you try develop `Calculus.jl` with QuadGK ?

**Comment by ErikQQY** [comment]
@nesteiner
https://github.com/JuliaMath/Calculus.jl/blob/9cc56d2435a3d88f11ae7e63a4d1e33f789fb095/README.md?plain=1#L100-L103
